// config.bin - 20:04:04 02/05/26, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class 203rd_Cadian_ACE_Arsenal_Extended {
		requiredAddons[] = {"A3_Data_F", "aceax_main", "aceax_arsenal", "203rd_Cadian_Equipment"};
		requiredVersion = 0.1;
		units[] = {};
		weapons[] = {};
	};
};

class XtdGearModels {
	class CfgVehicles {
		class 203rd_Cadian_Backpacks {
			label = "$STR_TAG_203rdMW_Menu_Backpack_label";
			author = "203rd Cadian";
			options[] = {"Munitorum","Bandolier","Field"};
			class Munitorum {
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_Backpack_label_Munitorum";
				values[] = {"none","no_gear","nozhny","skatka","MED","nozhny_lopata","skatka_lopata","skatka_lopata_nozhny","skatka_shovel_pouches","skatka_lopata_nozhny_pouches","shtorm","shtorm_knife"};				                                                                                                                                   
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class no_gear{
					label="$STR_TAG_203rdMW_Menu_Backpack_no_gear";
				};
				class nozhny{
					label="$STR_TAG_203rdMW_Menu_Backpack_nozhny";
				};
				class skatka{
					label="$STR_TAG_203rdMW_Menu_Backpack_skatka";
				};
				class MED{
					label="$STR_TAG_203rdMW_Menu_Backpack_MED";
				};
				class nozhny_lopata{
					label="$STR_TAG_203rdMW_Menu_Backpack_nozhny_lopata";
				};
				class skatka_lopata{
					label="$STR_TAG_203rdMW_Menu_Backpack_skatka_lopata";
				};
				class skatka_lopata_nozhny{
					label="$STR_TAG_203rdMW_Menu_Backpack_skatka_lopata_nozhny";
				};
				class skatka_shovel_pouches{
					label="$STR_TAG_203rdMW_Menu_Backpack_skatka_shovel_pouches";
				};
				class skatka_lopata_nozhny_pouches{
					label="$STR_TAG_203rdMW_Menu_Backpack_skatka_lopata_nozhny_pouches";
				};
				class shtorm{
					label="$STR_TAG_203rdMW_Menu_Backpack_light";
				};
				class shtorm_knife{
					label="$STR_TAG_203rdMW_Menu_Backpack_light_knife";
				};
		    };
			class Bandolier {
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_Backpack_label_bandolier";
				values[] = {"none","webbingV1","webbingV2","webbingV3","Bandolier"};				                                                                                                                                   
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class webbingV1{
					label="$STR_TAG_203rdMW_Menu_Backpack_webbing_1";
				};
				class webbingV2{
					label="$STR_TAG_203rdMW_Menu_Backpack_webbing_2";
				};
				class webbingV3{
					label="$STR_TAG_203rdMW_Menu_Backpack_webbing_3";
				};
				class Bandolier{
					label="$STR_TAG_203rdMW_Menu_Backpack_bandolier";
				};
		    };
			class Field {
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_Backpack_label_field";
				values[] = {"none","standart","kolobok","vox_v1","vox_v2","invisible","kasr_cable","kasr_cable_NC","rocket"};				                                                                                                                                   
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class standart{
					label="$STR_TAG_203rdMW_Menu_Backpack_standart";
				};
				class kolobok{
					label="$STR_TAG_203rdMW_Menu_Backpack_kolobok";
				};
				class vox_v1{
					label="$STR_TAG_203rdMW_Menu_Backpack_vox_v1";
				};
				class vox_v2{
					label="$STR_TAG_203rdMW_Menu_Backpack_vox_v2";
				};
				class invisible{
					label="$STR_TAG_203rdMW_Menu_Backpack_invisible";
				};
				class kasr_cable{
					label="$STR_TAG_203rdMW_Menu_Backpack_kasr_cable";
				};
				class kasr_cable_NC{
					label="$STR_TAG_203rdMW_Menu_Backpack_kasr_cable_NC";
				};
				class rocket{
					label="$STR_TAG_203rdMW_Menu_Backpack_rocket";
				};
		    };
	    };
    };
	class CfgWeapons {
		class 203rd_Cadian_Helmets {
			label = "$STR_TAG_203rdMW_Menu_Helmets_label";
			author = "203rd Cadian";
			options[] = {"ubor","specs","additionals","rank","named"};
			
			class ubor {
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_Helmets_label_hats";
				values[] = {"none","patrol_cap", "officer_cap", "beret","tanker","vox"};
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class patrol_cap {
					label = "$STR_TAG_203rdMW_Menu_Helmets_patrol_cap";
				};
				class officer_cap {
					label = "$STR_TAG_203rdMW_Menu_Helmets_officer_cap";
				};
				class beret {
					label = "$STR_TAG_203rdMW_Menu_label_beret";
				};
				class tanker{
					label="$STR_TAG_203rdMW_Menu_Helmets_tanker";
				};
				class vox{
					label="$STR_TAG_203rdMW_Menu_Helmets_Vox";
				};
			};
			class specs{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_helmets_specs";
				values[] = {"none","guardsman", "medicae", "kasrkin"};
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class guardsman{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_specs_guardsman";
				};
				class medicae{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_specs_medicae";
				};
				class kasrkin{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_specs_kasrkin";
				};
			};
			class additionals{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_helmets_adds";
				values[] = {"none","clear","goggle_up","goggle_down","rebreather","rebreather_OG","rebreather_OG_NV"};
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class clear{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_adds_clear";
				};
				class goggle_up{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_adds_goggles_up";
				};
				class goggle_down{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_adds_goggle_down";
				};
				class rebreather{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_adds_rebreather";
				};
				class rebreather_OG{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_adds_rebreather_OG";
				};
				class rebreather_OG_NV{
					label = "$STR_TAG_203rdMW_Menu_label_helmets_adds_rebreather_OG_NV";
				};
			};
			class rank{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_helmets_rank";
				values[] = {"WS","troop","serg","OFC"};
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class WS{
					label="$STR_TAG_203rdMW_Menu_label_helmets_rank_WS";
				};
				class Troop{
					label="$STR_TAG_203rdMW_Menu_label_helmets_rank_Troop";
				};
				class Serg{
					label="$STR_TAG_203rdMW_Menu_label_helmets_rank_Serg";
				};
				class OFC{
					label="$STR_TAG_203rdMW_Menu_label_helmets_rank_OFC";
				};
			};
			class named{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_helmets_named";
				values[] = {"none","muller"};
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class muller{
					label="$STR_TAG_203rdMW_Menu_label_helmets_named_Muller";
				};
			};
		};
		class 203rd_Cadian_Vests{
			label = "$STR_TAG_203rdMW_Menu_label_vest";
			author = "203rd Cadian";
			options[] = {"type","variant","spec","rank","named"};
			
			class type{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_vest_type";
				values[] = {"none","light", "medium", "heavy"};
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class light{
					label="$STR_TAG_203rdMW_Menu_label_vest_type_light";
				};
				class medium{
					label="$STR_TAG_203rdMW_Menu_label_vest_type_medium";
				};
				class heavy{
					label="$STR_TAG_203rdMW_Menu_label_vest_type_heavy";
				};
			};
			class variant{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_vest_variant";
				values[] = {"none","v1", "v2", "v3","v4"};
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class v1{
					label="$STR_TAG_203rdMW_Menu_label_vest_variant_1";
				};
				class v2{
					label="$STR_TAG_203rdMW_Menu_label_vest_variant_2";
				};
				class v3{
					label="$STR_TAG_203rdMW_Menu_label_vest_variant_3";
				};
				class v4{
					label="$STR_TAG_203rdMW_Menu_label_vest_variant_4";
				};
			};
			class spec{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_vest_spec";
				values[] = {"none","troop", "med", "HWT","SWT","kasr","kasr_med","kasr_hwt","tank"};
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class troop{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_troop";
				};
				class med{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_med";
				};
				class HWT{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_HWT";
				};
				class SWT{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_SWT";
				};
				class kasr{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_kasr";
				};
				class kasr_med{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_kasr_med";
				};
				class kasr_hwt{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_kasr_hwt";
				};
				class kasr_swt{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_kasr_swt";
				};
				class tank{
					label="$STR_TAG_203rdMW_Menu_label_vest_spec_tank";
				};
			};
			class rank{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_vest_rank";
				values[] = {"none","pvt","vet", "sgt", "ofc"};
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class pvt{
					label="$STR_TAG_203rdMW_Menu_label_vest_rank_pvt";
				};
				class vet{
					label="$STR_TAG_203rdMW_Menu_label_vest_rank_vet";
				};
				class sgt{
					label="$STR_TAG_203rdMW_Menu_label_vest_rank_sgt";
				};
				class ofc{
					label="$STR_TAG_203rdMW_Menu_label_vest_rank_ofc";
				};
			};
			class named{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_vest_named";
				values[] = {"none","rehis", "merek","muller","steel", "brimm","krass","psy"};
				
				class none{
					label="$STR_TAG_203rdMW_Menu_none_label";
				};
				class rehis{
					label="$STR_TAG_203rdMW_Menu_label_vest_named_rehis";
				};
				class merek{
					label="$STR_TAG_203rdMW_Menu_label_vest_named_merek";
				};
				class muller{
					label="$STR_TAG_203rdMW_Menu_label_vest_named_muller";
				};
				class steel{
					label="$STR_TAG_203rdMW_Menu_label_vest_named_steel";
				};
				class brimm{
					label="$STR_TAG_203rdMW_Menu_label_vest_named_brimm";
				};
				class krass{
					label="$STR_TAG_203rdMW_Menu_label_vest_named_SOLNCELIKIY_KOMANDIR_KAPITAN_krass";
				};
				class psy{
					label="$STR_TAG_203rdMW_Menu_label_vest_named_psy";
				};
			};
		};
		class 203rd_Cadian_uniform{
			label = "$STR_TAG_203rdMW_Menu_label_uni";
			author = "203rd Cadian";
			options[] = {"tip","camo","speci","armor","rang"};
			class tip
			{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_uni_tip";
				values[] = {"norm", "rolled", "parka"};
				class norm{
					label="$STR_TAG_203rdMW_Menu_uni_tip_norm";
				};
				class rolled{
					label="$STR_TAG_203rdMW_Menu_uni_tip_rolled";
				};
				class parka{
					label="$STR_TAG_203rdMW_Menu_uni_tip_parka";
				};
			};
			class camo
			{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_label_uni_camo";
				values[] = {"none","no_camo", "half_camo", "camo"};
				
				class no_camo{
					label="$STR_TAG_203rdMW_Menu_uni_camo_no_camo";
				};
				class half_camo{
					label="$STR_TAG_203rdMW_Menu_uni_camo_half_camo";
				};
				class camo{
					label="$STR_TAG_203rdMW_Menu_uni_camo_camo";
				};
			};
			class speci
			{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_uni_speci";
				values[] = {"troopic", "medi","karasik"};
				
				class troopic{
					label="$STR_TAG_203rdMW_Menu_uni_speci_troopic";
				};
				class medi{
					label="$STR_TAG_203rdMW_Menu_uni_speci_med";
				};
				class karasik{
					label="$STR_TAG_203rdMW_Menu_uni_speci_kasr";
				};
			};
			class armor
			{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_armory";
				values[] = {"none","basic", "knee_pads", "TA","full","kn_brac"};
				class basic{
					label="$STR_TAG_203rdMW_Menu_armor_basic";
				};
				class knee_pads{
					label="$STR_TAG_203rdMW_Menu_armor_knee_pads";
				};
				class TA{
					label="$STR_TAG_203rdMW_Menu_armor_TA";
				};
				class full{
					label="$STR_TAG_203rdMW_Menu_armor_full";
				};
				class kn_brac{
					label="$STR_TAG_203rdMW_Menu_armor_kn_brac";
				};
			};
			class rang
			{
				alwaysSelectable = 1;
				changeingame = 0;
				label = "$STR_TAG_203rdMW_Menu_rang";
				values[] = {"Private", "Sergants", "Officers"};
				class Private{
					label="$STR_TAG_203rdMW_Menu_rang_Private";
				};
				class Sergants{
					label="$STR_TAG_203rdMW_Menu_rang_Sergants";
				};
				class Officers{
					label="$STR_TAG_203rdMW_Menu_rang_Officers";
				};
			};
		};
	};
};

class XtdGearInfos {

	class CfgVehicles {
		class 203rd_CadianBackpack2 {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "no_gear";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2Medicae {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "MED";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2BR {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "skatka";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2BRSH {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "skatka_lopata";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2BRSHP {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "skatka_shovel_pouches";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2BRSHPK {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "skatka_lopata_nozhny_pouches";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2BRSHK {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "skatka_lopata_nozhny";
			Bandolier = "none";
		Field = "none";
		};
		class 203rd_CadianBackpack2K {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "nozhny";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2KSH {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "nozhny_lopata";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2Light {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "shtorm";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianBackpack2LightKnife {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "shtorm_light";
			Bandolier = "none";
			Field = "none";
		};
		class 203rd_CadianWebbing_co {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Field = "none";
			Bandolier = "webbingV1";
		};
		class 203rd_CadianWebbing2BP_co {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Field = "none";
			Bandolier = "webbingV2";
		};
		class 203rd_CadianWebbing3BP_co {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Field = "none";
			Bandolier = "webbingV3";
		};
		class 203rd_CadianBandolier_co {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Field = "none";
			Bandolier = "Bandolier";
		};
		class 203rd_CadianBackpack1_co {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Bandolier = "none";
			Field = "standart";
		};
		class 203rd_Backpack_Invisible {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Bandolier = "none";
			Field = "invisible";
		};
		class 203rd_Backpack_CarryAll {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Bandolier = "none";
			Field = "kolobok";
		};
		class 203rd_Backpack_Vox {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Bandolier = "none";
			Field = "vox_v1";
		};
		class FIG_CadianVoxBackpackGrey {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Bandolier = "none";
			Field = "vox_v2";
		};
		class 203rd_KasrkinPowerpack {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Bandolier = "none";
			Field = "kasr_power";
		};
		class 203rd_KasrkinPowerpack_NC {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Bandolier = "none";
			Field = "kasr_power_NC";
		};
		class ic_cad_RocketPack_NoStraps {
			model = "203rd_Cadian_Backpacks";
			Munitorum = "none";
			Bandolier = "none";
			Field = "rocket";
		};
	};
	class CfgWeapons {
		//helmets
		class 203rd_Patrol_Cap
		{
			model = "203rd_Cadian_Helmets";
			ubor = "patrol_cap";
			specs = "none";
			additionals = "none";
			rank = "none";
			named = "none";
		};
		class 203rd_Beret
		{
			model = "203rd_Cadian_Helmets";
			ubor = "beret";
			specs = "none";
			additionals = "none";
			rank = "none";
			named = "none";
		};
		class 203rd_Officer_Cap
		{
			model = "203rd_Cadian_Helmets";
			ubor = "officer_cap";
			specs = "none";
			additionals = "none";
			rank = "none";
			named = "none";
		};
		class 203rd_Tanker_Cap
		{
			model = "203rd_Cadian_Helmets";
			ubor = "tanker";
			specs = "none";
			additionals = "none";
			rank = "none";
			named = "none";
		};
		class 203rd_CadianVoxHelm
		{
			model = "203rd_Cadian_Helmets";
			ubor = "vox";
			specs = "none";
			additionals = "none";
			rank = "none";
			named = "none";
		};
		class 203rd_Helmet
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "clear";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_Mask
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_NV
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG_NV";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_GU
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_up";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_GD
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_down";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_Medicae
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "clear";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_Mask_Medicae
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "rebreather";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_Medicae
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "rebreather_OG";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_NV_Medicae
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "rebreather_OG_NV";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_GU_Medicae
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "goggle_up";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_GD_Medicae
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "goggle_down";
			rank = "troop";
			named = "none";
		};
		class 203rd_Helmet_Whiteshield
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "clear";
			rank = "WS";
			named = "none";
		};
		class 203rd_Helmet_Mask_Whiteshield
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather";
			rank = "WS";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_Whiteshield
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG";
			rank = "WS";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_NV_Whiteshield
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG_NV";
			rank = "WS";
			named = "none";
		};
		class 203rd_Helmet_GU_Whiteshield
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_up";
			rank = "WS";
			named = "none";
		};
		class 203rd_Helmet_GD_Whiteshield
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_down";
			rank = "WS";
			named = "none";
		};
		class 203rd_Helmet_Sergeant
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "clear";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Mask_Sergeant
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_Sergeant
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_NV_Sergeant
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG_NV";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_GU_Sergeant
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_up";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_GD_Sergeant
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_down";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Sergeant_M
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "clear";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Mask_Sergeant_M
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "rebreather";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_Sergeant_M
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "rebreather_OG";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_NV_Sergeant_M
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "rebreather_OG_NV";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_GU_Sergeant_M
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "goggle_up";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_GD_Sergeant_M
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "medicae";
			additionals = "goggle_down";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Officer
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "clear";
			rank = "OFC";
			named = "none";
		};
		class 203rd_Helmet_Mask_Officer
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather";
			rank = "OFC";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_Officer
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG";
			rank = "OFC";
			named = "none";
		};
		class 203rd_Helmet_Mask_OG_NV_Officer
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG_NV";
			rank = "OFC";
			named = "none";
		};
		class 203rd_Helmet_GU_Officer
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_up";
			rank = "OFC";
			named = "none";
		};
		class 203rd_Helmet_GD_Officer
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_down";
			rank = "OFC";
			named = "none";
		};
		class 203rd_Helmet_Mask_Kasrkin
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "kasrkin";
			additionals = "rebreather";
			rank = "guardsman";
			named = "none";
		};
		class 203rd_Helmet_Mask_Kasrkin_OG
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "kasrkin";
			additionals = "rebreather_OG";
			rank = "guardsman";
			named = "none";
		};
		class 203rd_Helmet_Mask_Kasrkin_OG_NV
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "kasrkin";
			additionals = "rebreather_OG_NV";
			rank = "guardsman";
			named = "none";
		};
		class 203rd_Helmet_Mask_Kasrkin_Sergeant
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "kasrkin";
			additionals = "rebreather";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Mask_Kasrkin_Sergeant_OG
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "kasrkin";
			additionals = "rebreather";
			rank = "serg_OG";
			named = "none";
		};
		class 203rd_Helmet_Mask_Kasrkin_Sergeant_OG_NV
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "kasrkin";
			additionals = "rebreather_OG_NV";
			rank = "serg";
			named = "none";
		};
		class 203rd_Helmet_Sergeant_Muller
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "clear";
			rank = "serg";
			named = "muller";
		};
		class 203rd_Sergeant_Muller_Mask
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "rebreather_OG";
			rank = "serg";
			named = "muller";
		};
		class 203rd_Sergeant_Muller_GU
		{
			model = "203rd_Cadian_Helmets";
			ubor = "none";
			specs = "guardsman";
			additionals = "goggle_up";
			rank = "serg";
			named = "muller";
		};
		
		//Vests
		class 203rd_Flakweave_Vest{
			model="203rd_Cadian_Vests";
			type="light";
			variant="none";
			spec="tank";
			rank="none";
			named="none";
		};
		class 203rd_Armor{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V1{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V1_Merek{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="troop";
			rank="pvt";
			named="merek";
		};
		class 203rd_Armor_V2{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_CadianArmor_V2_rehisastik{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="troop";
			rank="pvt";
			named="rehis";
		};
		class 203rd_Armor_V3{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V4{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="med";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V1_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="med";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V2_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="med";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V3_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="med";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V4_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="med";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_Sergeant_Medicae_1{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_Sergeant_Medicae_2{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_Sergeant_Medicae_3{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_Sergeant_Medicae_4{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_Veteran{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="troop";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V1_Veteran{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="troop";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V2_Veteran{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="troop";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V3_Veteran{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="troop";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V4_Veteran{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="troop";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_Veteran_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="med";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V1_Veteran_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="med";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V2_Veteran_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="med";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V3_Veteran_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="med";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V4_Veteran_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="med";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_Sergeant{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="troop";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_V1_Sergeant{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="troop";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_V2_Sergeant{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="troop";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_V3_Sergeant{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="troop";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_V3_Voodoo{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="troop";
			rank="sgt";
			named="muller";
		};
		class 203rd_Armor_V4_Sergeant{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="troop";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_Sergeant_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_V1_Sergeant_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_V2_Sergeant_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_V3_Sergeant_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_V4_Sergeant_Medicae{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="med";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_Officer{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="troop";
			rank="ofc";
			named="none";
		};
		class 203rd_Armor_V1_Officer{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="troop";
			rank="ofc";
			named="none";
		};
		class 203rd_Armor_V2_Officer{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="troop";
			rank="ofc";
			named="none";
		};
		class 203rd_Armor_V3_Officer{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="troop";
			rank="ofc";
			named="none";
		};
		class 203rd_Armor_V3_Vest{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="troop";
			rank="ofc";
			named="krass";
		};
		class 203rd_Armor_V4_Officer{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="troop";
			rank="ofc";
			named="none";
		};
		class 203rd_Armor_V4_Officer_Brimmy{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="troop";
			rank="ofc";
			named="brimm";
		};
		class 203rd_Armor_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V1_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V2_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V3_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V4_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_Veteran_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V1_Veteran_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V2_Veteran_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V3_Veteran_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V4_Veteran_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V1_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V2_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V3_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_V4_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="SWT";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_Veteran_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="none";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V1_Veteran_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v1";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V2_Veteran_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v2";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V3_Veteran_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v3";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_V4_Veteran_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="medium";
			variant="v4";
			spec="SWT";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_Kasrkin{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_Kasrkin_Medicae{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr_med";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_Kasrkin_Veteran_Medicae{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr_med";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_Kasrkin_Veteran{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_Kasrkin_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr_hwt";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_Kasrkin_Veteran_HeavyWeapons{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr_hwt";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_Kasrkin_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr_swt";
			rank="pvt";
			named="none";
		};
		class 203rd_Armor_Kasrkin_Veteran_SpecialWeapons{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr_swt";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_Kasrkin_Sergeant{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr";
			rank="sgt";
			named="none";
		};
		class 203rd_Armor_Kasrkin_Sergeant_Steel{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="kasr";
			rank="sgt";
			named="steel";
		};
		class 203rd_Armor_heavyarmour_Officer{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="troop";
			rank="ofc";
			named="none";
		};
		class 203rd_Armor_heavyarmour_Officer_Vest{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="troop";
			rank="ofc";
			named="krass";
		};
		class 203rd_Armor_heavyarmour_Veteran{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="troop";
			rank="vet";
			named="none";
		};
		class 203rd_Armor_heavyarmour_Sergeant{
			model="203rd_Cadian_Vests";
			type="heavy";
			variant="none";
			spec="troop";
			rank="sgt";
			named="none";
		};
		class 203rd_Light_Armor{
			model="203rd_Cadian_Vests";
			type="light";
			variant="none";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_Light_Armor_PSY{
			model="203rd_Cadian_Vests";
			type="light";
			variant="none";
			spec="troop";
			rank="pvt";
			named="psy";
		};
		class 203rd_Light_Armor_V1{
			model="203rd_Cadian_Vests";
			type="light";
			variant="v1";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_Light_Armor_V2{
			model="203rd_Cadian_Vests";
			type="light";
			variant="v2";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_Light_Armor_V3{
			model="203rd_Cadian_Vests";
			type="light";
			variant="v3";
			spec="troop";
			rank="pvt";
			named="none";
		};
		class 203rd_Light_Armor_V4{
			model="203rd_Cadian_Vests";
			type="light";
			variant="v4";
			spec="troop";
			rank="pvt";
			named="none";
		};
		//uniforms yepta
		class 203rd_Uniform_1_w
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="basic";
			rang="Private";
		};
		class 203rd_Uniform_1_w_1
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="basic";
			rang="Private";
		};
		class 203rd_Uniform_1_w_2
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="troopic";
			armor="basic";
			rang="Private";
		};
		class 203rd_Uniform_1_w_3
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="troopic";
			armor="basic";
			rang="Sergants";
		};
		class 203rd_Uniform_1_w_4
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="basic";
			rang="Sergants";
		};
		class 203rd_Uniform_1_w_5
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="basic";
			rang="Sergants";
		};
		class 203rd_Uniform_2_w
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_2_w_1
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_2_w_2
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="troopic";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_2_w_3
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="knee_pads";
			rang="Sergants";
		};
		class 203rd_Uniform_2_w_4
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="knee_pads";
			rang="Sergants";
		};
		class 203rd_Uniform_2_w_5
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="troopic";
			armor="knee_pads";
			rang="Sergants";
		};
		class 203rd_Uniform_3_w
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_3_w_1
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_3_w_2
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="troopic";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_3_w_3
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="TA";
			rang="Sergants";
		};
		class 203rd_Uniform_3_w_4
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="troopic";
			armor="TA";
			rang="Sergants";
		};
		class 203rd_Uniform_3_w_5
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="TA";
			rang="Sergants";
		};
		class 203rd_Uniform_4_w
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="full";
			rang="Private";
		};
		class 203rd_Uniform_4_w_1
		{	
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="full";
			rang="Private";
		};
		class 203rd_Uniform_4_w_2
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="troopic";
			armor="full";
			rang="Private";
		};
		class 203rd_Uniform_4_w_3
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="full";
			rang="Sergants";
		};
		class 203rd_Uniform_4_w_4
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="troopic";
			armor="full";
			rang="Sergants";
		};
		class 203rd_Uniform_4_w_5
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="full";
			rang="Sergants";
		};
		class 203rd_Uniform_5_w
		{
			model="203rd_Cadian_uniform";
			tip="parka";
			camo="no_camo";
			speci="troopic";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_5_w_1
		{
			model="203rd_Cadian_uniform";
			tip="parka";
			camo="camo";
			speci="troopic";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_5_w_2
		{
			model="203rd_Cadian_uniform";
			tip="parka";
			camo="no_camo";
			speci="troopic";
			armor="knee_pads";
			rang="Officers";
		};
		class 203rd_Uniform_5_w_3
		{
			model="203rd_Cadian_uniform";
			tip="parka";
			camo="camo";
			speci="troopic";
			armor="knee_pads";
			rang="Sergants";
		};
		class 203rd_Uniform_6_w
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="troopic";
			armor="kn_brac";
			rang="Private";
		};
		class 203rd_Uniform_6_w_1
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="troopic";
			armor="kn_brac";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_1_w
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="no_camo";
			speci="troopic";
			armor="basic";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_1_w_1
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="camo";
			speci="troopic";
			armor="basic";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_1_w_2
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="half_camo";
			speci="troopic";
			armor="basic";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_2_w
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="no_camo";
			speci="troopic";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_2_w_1
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="camo";
			speci="troopic";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_2_w_2
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="half_camo";
			speci="troopic";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_3_w
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="no_camo";
			speci="troopic";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_3_w_1
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="camo";
			speci="troopic";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_3_w_2
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="half_camo";
			speci="troopic";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_2_Medicae_w
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="no_camo";
			speci="medi";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_2_Medicae_w_1
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="camo";
			speci="medi";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_2_Medicae_w_2
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="half_camo";
			speci="medi";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_3_Medicae_w
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="no_camo";
			speci="medi";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_3_Medicae_w_1
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="camo";
			speci="medi";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_3_Medicae_w_2
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="half_camo";
			speci="medi";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_4_Medicae_w
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="no_camo";
			speci="medi";
			armor="full";
			rang="Private";
		};
		class 203rd_Uniform_4_Medicae_w_1
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="camo";
			speci="medi";
			armor="full";
			rang="Private";
		};
		class 203rd_Uniform_4_Medicae_w_2
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="half_camo";
			speci="medi";
			armor="full";
			rang="Private";
		};
		class 203rd_Uniform_5_Medicae_w
		{
			model="203rd_Cadian_uniform";
			tip="parka";
			camo="no_camo";
			speci="medi";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_5_Medicae_w_1
		{
			model="203rd_Cadian_uniform";
			tip="parka";
			camo="camo";
			speci="medi";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_6_Medicae
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="medi";
			armor="kn_brac";
			rang="Private";
		};
		class 203rd_Uniform_6_Medicae_v_1
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="half_camo";
			speci="medi";
			armor="kn_brac";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_2_Medicae_w
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="no_camo";
			speci="medi";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_2_Medicae_w_1
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="camo";
			speci="medi";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_2_Medicae_w_2
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="half_camo";
			speci="medi";
			armor="knee_pads";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_3_Medicae_w
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="no_camo";
			speci="medi";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_3_Medicae_w_1
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="camo";
			speci="medi";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_Rolled_3_Medicae_w_2
		{
			model="203rd_Cadian_uniform";
			tip="rolled";
			camo="half_camo";
			speci="medi";
			armor="TA";
			rang="Private";
		};
		class 203rd_Uniform_Kasrkin_w
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="no_camo";
			speci="karasik";
			armor="full";
			rang="Private";
		};
		class 203rd_Uniform_Kasrkin_w_1
		{
			model="203rd_Cadian_uniform";
			tip="norm";
			camo="camo";
			speci="karasik";
			armor="full";
			rang="Private";
		};
	};
};
