	class TIOW_LR_BattleCannon: Tank_F
	{
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				turretInfoType="RscOptics_ICP_MBT01_Gunner_01";
				gunnerOpticsModel="\A3\weapons_f\reticle\Optics_Gunner_02_F";
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"Ti"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_MBT_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_MBT_01_W.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
				class Turrets: Turrets
				{
					class CommanderOptics: NewTurret
					{
						turretInfoType="RscOptics_ICP_MBT01_Gunner_01";
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_Commander_01_W.p3d";
						class OpticsIn: Optics_Commander_02
						{
							class Wide: Wide
							{
								gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_Commander_01_W.p3d";
								gunnerOpticsEffect[]=
								{
									"TankGunnerOptics2",
									"OpticsBlur1",
									"OpticsCHAbera1"
								};
							};
							class Medium: Medium
							{
								gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_Commander_01_W.p3d";
								gunnerOpticsEffect[]=
								{
									"TankGunnerOptics2",
									"OpticsBlur1",
									"OpticsCHAbera1"
								};
							};
							class Narrow: Narrow
							{
								gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_Commander_01_W.p3d";
								gunnerOpticsEffect[]=
								{
									"TankGunnerOptics2",
									"OpticsBlur1",
									"OpticsCHAbera1"
								};
							};
						};
					};
				};
			};
			class FrontGunner: NewTurret
			{
				turretInfoType="";
				gunnerOpticsModel="\A3\weapons_f\reticle\Optics_Gunner_02_F";
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"Ti"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
			class LHBGunner: NewTurret
			{
				turretInfoType="";
				gunnerOpticsModel="\A3\weapons_f\reticle\Optics_Gunner_02_F";
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"Ti"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
			class RHBGunner: NewTurret
			{
				turretInfoType="";
				gunnerOpticsModel="\A3\weapons_f\reticle\Optics_Gunner_02_F";
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"Ti"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
		};
	};
	class C203_vehicle_Tank_LR_BattleCannon_01: TIOW_LR_BattleCannon
	{
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_BC_TIOW";
		crew="203rd_02";
		side=1;
		scope=2;
		scopeCurator = 2;
		accuracy=1000;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy_TIOW";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\203Insignia_TIOW.paa",
			"vehicles\data\lemanRuss\TIOW\LR_203_TIOW_co.paa"
		};
	};
	class IC_Leman_Russ_02_base: Tank_F
	{
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"TI"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_MBT_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_MBT_01_W.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
			class Hull_turret: NewTurret
			{
				class ViewGunner: ViewOptics
				{
					initAngleX=-5;
					initAngleY=0;
					initFov=0.89999998;
					minFov=0.25;
					maxFov=1.25;
					minAngleX=-65;
					maxAngleX=85;
					minAngleY=-150;
					maxAngleY=150;
					minMoveX=-0.075000003;
					maxMoveX=0.075000003;
					minMoveY=-0.075000003;
					maxMoveY=0.075000003;
					minMoveZ=-0.075000003;
					maxMoveZ=0.1;
				};
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"TI"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
			class Left_Sponson_turret: Hull_turret
			{
				class ViewGunner: ViewOptics
				{
					initAngleX=-5;
					initAngleY=0;
					initFov=0.89999998;
					minFov=0.25;
					maxFov=1.25;
					minAngleX=-65;
					maxAngleX=85;
					minAngleY=-150;
					maxAngleY=150;
					minMoveX=-0.075000003;
					maxMoveX=0.075000003;
					minMoveY=-0.075000003;
					maxMoveY=0.075000003;
					minMoveZ=-0.075000003;
					maxMoveZ=0.1;
				};
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"TI"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
			class Right_Sponson_turret: Hull_turret
			{
				class ViewGunner: ViewOptics
				{
					initAngleX=-5;
					initAngleY=0;
					initFov=0.89999998;
					minFov=0.25;
					maxFov=1.25;
					minAngleX=-65;
					maxAngleX=85;
					minAngleY=-150;
					maxAngleY=150;
					minMoveX=-0.075000003;
					maxMoveX=0.075000003;
					minMoveY=-0.075000003;
					maxMoveY=0.075000003;
					minMoveZ=-0.075000003;
					maxMoveZ=0.1;
				};
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"TI"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
		};
	};
	class C203_vehicle_Tank_LR_BattleCannon_02: IC_Leman_Russ_02_base
	{
		side=1;
		scope=2;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy";
		crew="203rd_02";
		accuracy=1000;
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_BC";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\lemanRuss\ICP\LR_203_IC_hull_co.paa",
			"vehicles\data\lemanRuss\ICP\LR_203_IC_tracks_co.paa",
			"vehicles\data\lemanRuss\ICP\LR_203_IC_turret_co.paa",
			"vehicles\data\lemanRuss\ICP\LR_203_IC_gun_co.paa"
		};
		animationList[]=
		{
			"showDozerBlade",
			1,
			"ShowInsig_cadiangate",
			1,
			"ShowInsig_aquilaskull",
			1
		};
	};
	class TIOW_LR_Vanquisher: TIOW_LR_BattleCannon
	{
	};
	class C203_vehicle_Tank_LR_Vanquisher_01: TIOW_LR_Vanquisher
	{
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_Vanq_TIOW";
		crew="203rd_02";
		side=1;
		scope=2;
		accuracy=1000;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy_TIOW";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\203Insignia_TIOW.paa",
			"vehicles\data\lemanRuss\TIOW\LR_203_TIOW_co.paa"
		};
	};
	class IC_Leman_Russ_01_base: Tank_F
	{
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"TI"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_MBT_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_MBT_01_W.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
			class Hull_turret: NewTurret
			{
				class ViewGunner: ViewOptics
				{
					initAngleX=-5;
					initAngleY=0;
					initFov=0.89999998;
					minFov=0.25;
					maxFov=1.25;
					minAngleX=-65;
					maxAngleX=85;
					minAngleY=-150;
					maxAngleY=150;
					minMoveX=-0.075000003;
					maxMoveX=0.075000003;
					minMoveY=-0.075000003;
					maxMoveY=0.075000003;
					minMoveZ=-0.075000003;
					maxMoveZ=0.1;
				};
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"TI"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
			class Left_Sponson_turret: Hull_turret
			{
				class ViewGunner: ViewOptics
				{
					initAngleX=-5;
					initAngleY=0;
					initFov=0.89999998;
					minFov=0.25;
					maxFov=1.25;
					minAngleX=-65;
					maxAngleX=85;
					minAngleY=-150;
					maxAngleY=150;
					minMoveX=-0.075000003;
					maxMoveX=0.075000003;
					minMoveY=-0.075000003;
					maxMoveY=0.075000003;
					minMoveZ=-0.075000003;
					maxMoveZ=0.1;
				};
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"TI"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
			class Right_Sponson_turret: Hull_turret
			{
				class ViewGunner: ViewOptics
				{
					initAngleX=-5;
					initAngleY=0;
					initFov=0.89999998;
					minFov=0.25;
					maxFov=1.25;
					minAngleX=-65;
					maxAngleX=85;
					minAngleY=-150;
					maxAngleY=150;
					minMoveX=-0.075000003;
					maxMoveX=0.075000003;
					minMoveY=-0.075000003;
					maxMoveY=0.075000003;
					minMoveZ=-0.075000003;
					maxMoveZ=0.1;
				};
				class OpticsIn
				{
					class Wide: ViewOptics
					{
						initAngleX=0;
						minAngleX=-30;
						maxAngleX=30;
						initAngleY=0;
						minAngleY=-100;
						maxAngleY=100;
						initFov=0.30000001;
						minFov=0.30000001;
						maxFov=0.30000001;
						visionMode[]=
						{
							"Normal",
							"NVG",
							"TI"
						};
						thermalMode[]={4};
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_W.p3d";
						gunnerOpticsEffect[]=
						{
							"TankGunnerOptics2",
							"OpticsBlur1",
							"OpticsCHAbera1"
						};
					};
					class Narrow: Wide
					{
						gunnerOpticsModel="\IC_Weapons_base\Reticle\IC_Reticle_APC_01_N.p3d";
						initFov=0.028000001;
						minFov=0.028000001;
						maxFov=0.028000001;
					};
				};
			};
		};
	};
	class C203_vehicle_Tank_LR_Vanquisher_02: IC_Leman_Russ_01_base
	{
		side=1;
		scope=2;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy";
		crew="203rd_02";
		accuracy=1000;
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_Vanq";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\lemanRuss\ICP\LR_203_IC_hull_co.paa",
			"vehicles\data\lemanRuss\ICP\LR_203_IC_tracks_co.paa",
			"vehicles\data\lemanRuss\ICP\LR_203_IC_turret_co.paa",
			"vehicles\data\lemanRuss\ICP\LR_203_IC_gun_co.paa"
		};
		animationList[]=
		{
			"showDozerBlade",
			1,
			"ShowInsig_cadiangate",
			1,
			"ShowInsig_aquilaskull",
			1
		};
		class textureSources
		{
			class C203
			{
				displayName="203rd Standard";
				author="CannonFodderMK4";
				textures[]=
				{
					"vehicles\data\lemanRuss\ICP\LR_203_IC_hull_co.paa",
					"vehicles\data\lemanRuss\ICP\LR_203_IC_tracks_co.paa",
					"vehicles\data\lemanRuss\ICP\LR_203_IC_turret_co.paa",
					"vehicles\data\lemanRuss\ICP\LR_203_IC_gun_co.paa"
				};
				factions[]={};
			};
		};
		textureList[]=
		{
			"C203",
			1
		};
	};
	class TIOW_LR_Conqueror: TIOW_LR_BattleCannon
	{
	};
	class C203_vehicle_Tank_LR_Conqueror_01: TIOW_LR_Conqueror
	{
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_Conq_TIOW";
		crew="203rd_02";
		side=1;
		scope=2;
		accuracy=1000;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy_TIOW";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\203Insignia_TIOW.paa",
			"vehicles\data\lemanRuss\TIOW\LR_203_TIOW_co.paa"
		};
	};
	class TIOW_LR_Demolisher: TIOW_LR_BattleCannon
	{
	};
	class C203_vehicle_Tank_LR_Demolisher_01: TIOW_LR_Demolisher
	{
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_Demo_TIOW";
		crew="203rd_02";
		side=1;
		scope=2;
		accuracy=1000;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy_TIOW";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\203Insignia_TIOW.paa",
			"vehicles\data\lemanRuss\TIOW\LR_203_TIOW_co.paa"
		};
	};
	class TIOW_LR_Exterminator: TIOW_LR_BattleCannon
	{
	};
	class C203_vehicle_Tank_LR_Exterminator_01: TIOW_LR_Exterminator
	{
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_Exter_TIOW";
		crew="203rd_02";
		side=1;
		scope=2;
		accuracy=1000;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy_TIOW";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\203Insignia_TIOW.paa",
			"vehicles\data\lemanRuss\TIOW\LR_203_TIOW_co.paa"
		};
	};
	class TIOW_LR_Executioner: TIOW_LR_BattleCannon
	{
	};
	class C203_vehicle_Tank_LR_Executioner_01: TIOW_LR_Executioner
	{
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_Exec_TIOW";
		crew="203rd_02";
		side=1;
		scope=2;
		accuracy=1000;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy_TIOW";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\203Insignia_TIOW.paa",
			"vehicles\data\lemanRuss\TIOW\LR_203_TIOW_co.paa"
		};
	};
	class TIOW_LR_Annihilator: TIOW_LR_BattleCannon
	{
	};
	class C203_vehicle_Tank_LR_Annihilator_01: TIOW_LR_Annihilator
	{
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_Annih_TIOW";
		crew="203rd_02";
		side=1;
		scope=2;
		accuracy=1000;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy_TIOW";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\203Insignia_TIOW.paa",
			"vehicles\data\lemanRuss\TIOW\LR_203_TIOW_co.paa"
		};
	};
	class TIOW_LR_Punisher: TIOW_LR_BattleCannon
	{
	};
	class C203_vehicle_Tank_LR_Punisher_01: TIOW_LR_Punisher
	{
		displayName="$STR_TAG_203rdMW_Heavy_Vehicle_Punish_TIOW";
		crew="203rd_02";
		side=1;
		scope=2;
		accuracy=1000;
		faction="203rdMW_Faction";
		editorSubcategory="203rdMW_Veh_Heavy_TIOW";
		typicalCargo[]=
		{
			"203rd_02"
		};
		hiddenSelectionsTextures[]=
		{
			"vehicles\data\203Insignia_TIOW.paa",
			"vehicles\data\lemanRuss\TIOW\LR_203_TIOW_co.paa"
		};
	};