class FIG_CadianCap;
class IC_scion_beret;
class IC_officer_cap_green;
class FIG_CadianHelm;
class FIG_CadianHelmMask;
class FIG_CadianHelmOGMask;
class FIG_CadianHelmOGMaskNV;
class FIG_CadianHelmGU;
class FIG_CadianHelmGD;
class IC_tanker_cap;
class HeadgearItem;
class 203rd_Patrol_Cap: FIG_CadianCap
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_PatCap";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianCap.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
		class ItemInfo: HeadgearItem
		{
			mass=10;
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianCap.p3d";
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianCap_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=12;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Beret: IC_scion_beret
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Beret";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_Beret.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
	};
	class 203rd_Officer_Cap: IC_officer_cap_green
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_OFC_Cap";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_Officer_Cap.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
		class ItemInfo: HeadgearItem
		{
			mass=2;
			uniformModel="\IC_cad_inf\Headgear\IC_officer_cap.p3d";
			modelSides[]={3,1};
			hiddenSelections[]=
			{
				"camo1"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=12;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Tanker_Cap: IC_tanker_cap
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Tanker_Cap";
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
	};
	class 203rd_Helmet: FIG_CadianHelm
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelm.p3d";
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\203rd_Equipment\data\203rd_CadianHelmet.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=30;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_Mask: FIG_CadianHelmMask
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Reb";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet.paa",
			"\203rd_Equipment\data\203rd_CadianMask.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelmMask.p3d";
			hiddenSelections[]=
			{
				"camo",
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"\203rd_Equipment\data\203rd_CadianHelmet.paa",
				"\203rd_Equipment\data\203rd_CadianMask.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=30;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_Mask_OG: FIG_CadianHelmOGMask
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_RebV2";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelmOGMask.p3d";
			hiddenSelections[]=
			{
				"camo",
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"\203rd_Equipment\data\203rd_CadianHelmet.paa",
				"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=30;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_Mask_OG_NV: FIG_CadianHelmOGMaskNV
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_RebV2_NV";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelmOGMaskNV.p3d";
			hiddenSelections[]=
			{
				"camo",
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"\203rd_Equipment\data\203rd_CadianHelmet.paa",
				"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=30;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_GU: FIG_CadianHelmGU
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_GU";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelmGU.p3d";
			hiddenSelections[]=
			{
				"camo",
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianHelmet_co.paa",
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianGoggles_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=30;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_GD: FIG_CadianHelmGD
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_GD";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
		ace_hearing_protection=0.80000001;
		ace_hearing_lowerVolume=0.60000002;
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelmGD.p3d";
			hiddenSelections[]=
			{
				"camo",
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianHelmet_co.paa",
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianGoggles_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=30;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_Medicae: 203rd_Helmet
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_M";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Medicae.paa"
		};
	};
	class 203rd_Helmet_Mask_Medicae: 203rd_Helmet_Mask
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_M_Reb";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Medicae.paa",
			"\203rd_Equipment\data\203rd_CadianMask_Medicae.paa"
		};
	};
	class 203rd_Helmet_Mask_OG_Medicae: 203rd_Helmet_Mask_OG
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_M_RebV2";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Medicae.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG_Medicae.paa"
		};
	};
	class 203rd_Helmet_Mask_OG_NV_Medicae: 203rd_Helmet_Mask_OG_NV
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_M_RebV2_NV";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Medicae.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG_Medicae.paa"
		};
	};
	class 203rd_Helmet_GU_Medicae: 203rd_Helmet_GU
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_M_GU";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Medicae.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles_Medicae.paa"
		};
	};
	class 203rd_Helmet_GD_Medicae: 203rd_Helmet_GD
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_M_GD";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Medicae.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles_Medicae.paa"
		};
	};
	class 203rd_Helmet_Whiteshield: 203rd_Helmet
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_WS";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Whiteshield.paa"
		};
	};
	class 203rd_Helmet_Mask_Whiteshield: 203rd_Helmet_Mask
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_WS_Reb";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Whiteshield.paa",
			"\203rd_Equipment\data\203rd_CadianMask.paa"
		};
	};
	class 203rd_Helmet_Mask_OG_Whiteshield: 203rd_Helmet_Mask_OG
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_WS_RebV2";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Whiteshield.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
	};
	class 203rd_Helmet_Mask_OG_NV_Whiteshield: 203rd_Helmet_Mask_OG_NV
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_WS_RebV2_NV";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Whiteshield.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
	};
	class 203rd_Helmet_GU_Whiteshield: 203rd_Helmet_GU
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_WS_GU";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Whiteshield.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
	};
	class 203rd_Helmet_GD_Whiteshield: 203rd_Helmet_GD
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_WS_GD";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Whiteshield.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
	};
	class 203rd_Helmet_Sergeant: 203rd_Helmet
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_SGT";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Sergeant.paa"
		};
	};
	class 203rd_Helmet_Mask_Sergeant: 203rd_Helmet_Mask
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_SGT_Reb";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Sergeant.paa",
			"\203rd_Equipment\data\203rd_CadianMask.paa"
		};
	};
	class 203rd_Helmet_Mask_OG_Sergeant: 203rd_Helmet_Mask_OG
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_SGT_RebV2";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Sergeant.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
	};
	class 203rd_Sergeant_Muller_Mask: 203rd_Helmet_Mask_OG
	{
		author="Brentwood";
		scope=2;
		displayName="203rd CadianHelmet Sergeant v1 (Muller)";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Sergeant_Muller.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
	};
	class 203rd_Sergeant_Muller_GU: 203rd_Helmet_GU
	{
		author="Brentwood";
		scope=2;
		displayName="203rd CadianHelmet Sergeant v2 (Muller)";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Sergeant_Muller.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
	};
	class 203rd_Helmet_Mask_OG_NV_Sergeant: 203rd_Helmet_Mask_OG_NV
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_SGT_RebV2_NV";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Sergeant.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
	};
	class 203rd_Helmet_GU_Sergeant: 203rd_Helmet_GU
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_SGT_GU";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Sergeant.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
	};
	class 203rd_Helmet_GD_Sergeant: 203rd_Helmet_GD
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_SGT_GD";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Sergeant.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
	};
	class 203rd_Helmet_Officer: 203rd_Helmet
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_OFC";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Officer.paa"
		};
	};
	class 203rd_Helmet_Mask_Officer: 203rd_Helmet_Mask
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_OFC_Reb";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Officer.paa",
			"\203rd_Equipment\data\203rd_CadianMask.paa"
		};
	};
	class 203rd_Helmet_Mask_OG_Officer: 203rd_Helmet_Mask_OG
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_OFC_RebV2";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Officer.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
	};
	class 203rd_Helmet_Mask_OG_NV_Officer: 203rd_Helmet_Mask_OG_NV
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_OFC_RebV2_NV";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Officer.paa",
			"\203rd_Equipment\data\203rd_CadianMaskOG.paa"
		};
	};
	class 203rd_Helmet_GU_Officer: 203rd_Helmet_GU
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_OFC_GU";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Officer.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
	};
	class 203rd_Helmet_GD_Officer: 203rd_Helmet_GD
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_OFC_GD";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Officer.paa",
			"\203rd_Equipment\data\203rd_CadianGoggles.paa"
		};
	};
	class 203rd_Helmet_Mask_Kasrkin: 203rd_Helmet_Mask
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Kasr";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Kasrkin.paa",
			"\203rd_Equipment\data\203rd_CadianMask_Kasrkin.paa"
		};
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelmMask.p3d";
			hiddenSelections[]=
			{
				"camo",
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianHelmet_co.paa",
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianMask_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=36;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_Mask_Kasrkin_OG: 203rd_Helmet_Mask_OG
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Kasr_RebV2";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Kasrkin.paa",
			"\203rd_Equipment\data\203rd_KasrkinMaskOG.paa"
		};
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelmOGMask.p3d";
			hiddenSelections[]=
			{
				"camo",
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianHelmet_co.paa",
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianOGMask_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=30;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_Mask_Kasrkin_OG_NV: 203rd_Helmet_Mask_OG_NV
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Kasr_RebV2_NV";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Kasrkin.paa",
			"\203rd_Equipment\data\203rd_KasrkinMaskOG.paa"
		};
		class ItemInfo: HeadgearItem
		{
			uniformModel="\FIG_Imperial_Guard\FIG_Cadians\FIG_CadianHelmOGMaskNV.p3d";
			hiddenSelections[]=
			{
				"camo",
				"camo1"
			};
			hiddenSelectionsTextures[]=
			{
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianHelmet_co.paa",
				"\FIG_Imperial_Guard\FIG_Cadians\data\CadianHelm\FIG_CadianOGMask_co.paa"
			};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=30;
					passThrough=0.5;
				};
			};
		};
	};
	class 203rd_Helmet_Mask_Kasrkin_Sergeant: 203rd_Helmet_Mask_Kasrkin
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Kasr_Serg";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Kasrkin_Sergeant.paa",
			"\203rd_Equipment\data\203rd_CadianMask_Kasrkin.paa"
		};
	};
	class 203rd_Helmet_Mask_Kasrkin_Sergeant_OG: 203rd_Helmet_Mask_Kasrkin_OG
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Kasr_Serg_RebV2";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Kasrkin_Sergeant.paa",
			"\203rd_Equipment\data\203rd_KasrkinMaskOG.paa"
		};
	};
	class 203rd_Helmet_Mask_Kasrkin_Sergeant_OG_NV: 203rd_Helmet_Mask_Kasrkin_OG_NV
	{
		author="Brentwood";
		scope=2;
		displayName="$STR_TAG_203rdMW_Helm_Kasr_Serg_RebV2_NV";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\203rd_Equipment\data\203rd_CadianHelmet_Kasrkin_Sergeant.paa",
			"\203rd_Equipment\data\203rd_KasrkinMaskOG.paa"
		};
	};